# Generated by Django 5.2.7 on 2025-11-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villaimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image file (preferred)', null=True, upload_to='villa_images/'),
        ),
        migrations.AlterField(
            model_name='villaimage',
            name='url',
            field=models.ImageField(blank=True, help_text='Fallback uploaded image (use ImageField, not a URL)', null=True, upload_to='villa_images/'),
        ),
    ]
