# Generated by Django 5.2.7 on 2025-11-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0002_villaimage_image_alter_villaimage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villaimage',
            name='url',
        ),
        migrations.AlterField(
            model_name='villaimage',
            name='image',
            field=models.ImageField(default=1, help_text='Upload image file (preferred)', upload_to='villa_images/'),
            preserve_default=False,
        ),
    ]
