# Generated by Django 5.2.7 on 2025-11-16 21:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0003_remove_villaimage_url_alter_villaimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='bookingrate',
            name='villa',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='villaimage',
            name='villa',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='villa',
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking_rate', models.JSONField(blank=True, default=dict, help_text="JSON format, e.g., { booking:  ['day':2, 'price': 500] }")),
                ('listing_type', models.CharField(choices=[('rent', 'For Rent'), ('sale', 'For Sale')], default='rent', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('archived', 'Archived'), ('sold', 'Sold')], default='draft', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('max_guests', models.PositiveIntegerField(default=1)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('has_pool', models.BooleanField(default=False)),
                ('amenities', models.JSONField(blank=True, default=dict, help_text="JSON format, e.g., {'wifi': true, 'pool': 'private'}")),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('signature_distinctions', models.JSONField(blank=True, help_text="List of unique features in JSON format, e.g., ['Ocean view', 'Private beach access']", null=True)),
                ('staff', models.JSONField(blank=True, help_text="List of staff details in JSON format, e.g., [{'role': 'chef', 'name': 'John Doe'}]", null=True)),
                ('calendar_link', models.URLField(blank=True, help_text='Link to external booking calendar (e.g., Google Calendar)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, help_text='Agent assigned to manage this villa', limit_choices_to={'role': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_villas', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload any file (image, video, PDF, etc.)', upload_to='property_media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('brochure', 'Brochure'), ('other', 'Other')], editable=False, help_text='The technical type of the file (auto-detected)', max_length=10)),
                ('category', models.CharField(choices=[('media', 'Media'), ('bedroom', 'Bedroom'), ('bathroom', 'Bathroom'), ('exterior', 'Exterior'), ('other', 'Other')], default='media', help_text='Categorize this media file (e.g., Bedroom, Exterior)', max_length=30)),
                ('caption', models.CharField(blank=True, help_text='Optional caption or description for the media file.', max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark this as the main/cover image for the listing.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Set the display order (0 comes first).')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='villas.property')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='villas.property'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
        migrations.DeleteModel(
            name='BookingRate',
        ),
        migrations.DeleteModel(
            name='VillaImage',
        ),
        migrations.DeleteModel(
            name='Villa',
        ),
    ]
