# Generated by Django 5.2.7 on 2025-11-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0004_remove_villa_amenities_remove_bookingrate_villa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='google_place_id',
            field=models.CharField(blank=True, help_text='Google Place ID for location integration', max_length=255, null=True),
        ),
    ]
