# Generated by Django 5.2.7 on 2025-11-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0005_property_google_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='google_place_id',
        ),
        migrations.AddField(
            model_name='property',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text='The ID of the Google Calendar for this property.', max_length=255, null=True),
        ),
    ]
