# Generated by Django 5.2.7 on 2025-11-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0006_remove_property_google_place_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='has_pool',
        ),
        migrations.AddField(
            model_name='property',
            name='pool',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
