# Generated by Django 5.2.7 on 2025-11-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0007_remove_property_has_pool_property_pool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='max_guests',
            new_name='add_guest',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='amenities',
            new_name='interior_amenities',
        ),
        migrations.AddField(
            model_name='property',
            name='outdoor_amenities',
            field=models.JSONField(blank=True, default=dict, help_text="JSON format, e.g., {'wifi': true, 'pool': 'private'}"),
        ),
    ]
