# Generated by Django 5.2.7 on 2025-11-19 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0008_rename_max_guests_property_add_guest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedroomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/bedrooms/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bedroom_images', to='villas.property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='villas.property')),
            ],
        ),
    ]
