# Generated by Django 5.2.7 on 2025-11-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0010_alter_bedroomimage_property_alter_property_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=22, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=22, max_digits=6, null=True),
        ),
    ]
