# Generated by Django 5.2.7 on 2025-11-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0014_property_check_in_property_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='check_in',
            field=models.TimeField(blank=True, help_text='Standard check-in time.', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='check_out',
            field=models.TimeField(blank=True, help_text='Standard check-out time.', null=True),
        ),
    ]
