# Generated by Django 5.2.7 on 2025-12-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0019_remove_property_google_calendar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20),
        ),
    ]
