# Generated by Django 5.2.7 on 2025-12-03 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0020_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bedroomimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bedroomimage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='concierge_services',
            field=models.JSONField(blank=True, default=dict, help_text="JSON format, e.g., {'airport_pickup': true, 'grocery_shopping': true}"),
        ),
        migrations.AddField(
            model_name='property',
            name='security_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='propertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='properties/videos/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_videos', to='villas.property')),
            ],
        ),
    ]
