# Generated by Django 5.2.7 on 2025-12-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0021_bedroomimage_description_bedroomimage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission rate (%) for the assigned agent.', max_digits=5),
        ),
        migrations.AddField(
            model_name='property',
            name='damage_deposit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Damage deposit amount for the property.', max_digits=10),
        ),
    ]
