# Generated by Django 5.2.7 on 2025-12-13 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0022_property_commission_rate_property_damage_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
