# Generated by Django 5.2.7 on 2025-12-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villas', '0023_alter_property_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
