# Generated by Django 5.2.7 on 2025-12-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('category', models.CharField(choices=[('marketing_materials', 'Marketing Materials'), ('property_viewings', 'Property Viewings'), ('property_management', 'Property Management'), ('commissions', 'Commissions'), ('technical_support', 'Technical Support')], default='marketing_materials', max_length=50)),
            ],
        ),
    ]
