# Generated by Django 5.2.7 on 2025-12-03 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resources/middle/')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_resources', to='resources.resource')),
            ],
        ),
    ]
