# Generated by Django 5.2.7 on 2025-12-03 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_middleresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='file',
        ),
    ]
