# Generated by Django 5.2.7 on 2025-12-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_resource_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MiddleResource',
            new_name='ResourceMedia',
        ),
    ]
