# Generated by Django 5.2.7 on 2025-12-03 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_rename_middleresource_resourcemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcemedia',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_resources', to='resources.resource'),
        ),
    ]
