# Generated by Django 5.2.7 on 2025-11-22 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_vila', '0003_contectus_created_at_contectus_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vilalisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vilalisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
